//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibProject.ConsoleApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LibProject.ConsoleApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Id&quot;: &quot;CC2B22AA-0941-44B3-A491-D9D6B788A50B&quot;,
        ///    &quot;FirstName&quot;: &quot;Patrick&quot;,
        ///    &quot;Surname&quot;: &quot;Rothfuss&quot;
        ///  },
        ///  {
        ///    &quot;Id&quot;: &quot;5DC96AC9-0903-44EA-A713-554CB0180D4E&quot;,
        ///    &quot;FirstName&quot;: &quot;Brent&quot;,
        ///    &quot;Surname&quot;: &quot;Weeks&quot;
        ///  },
        ///  {
        ///    &quot;Id&quot;: &quot;E494FB8A-B061-44B6-8813-09B22D77A7BB&quot;,
        ///    &quot;FirstName&quot;: &quot;Neil&quot;,
        ///    &quot;Surname&quot;: &quot;Gaiman&quot;
        ///  }
        ///].
        /// </summary>
        internal static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Id&quot;: &quot;F057F385-DBFC-4603-B432-CF8C5770CC1A&quot;,
        ///    &quot;Title&quot;: &quot;The Ocean at the End of the Lane&quot;,
        ///    &quot;AuthorId&quot;: &quot;E494FB8A-B061-44B6-8813-09B22D77A7BB&quot;,
        ///    &quot;ISBN&quot;: &quot;0062255657&quot;
        ///  },
        ///  {
        ///    &quot;Id&quot;: &quot;81E88010-78F7-47CA-B2F4-4D94730755EE&quot;,
        ///    &quot;Title&quot;: &quot;Coraline&quot;,
        ///    &quot;AuthorId&quot;: &quot;E494FB8A-B061-44B6-8813-09B22D77A7BB&quot;,
        ///    &quot;ISBN&quot;: &quot;0061139378&quot;
        ///  },
        ///  {
        ///    &quot;Id&quot;: &quot;C757606D-F8ED-47B3-94C8-A06B7808D54E&quot;,
        ///    &quot;Title&quot;: &quot;Neverwhere&quot;,
        ///    &quot;AuthorId&quot;: &quot;E494FB8A-B061-44B6-8813-09B22D77A7BB&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
    }
}
